baseurl = "https://intmaker.com/"
title = "Int Maker"
author = "Taras Kushnir"
languagecode = "en"
theme = "black-and-light"
canonifyURLs = true
enableRobotsTXT = true

pygmentsstyle       = "bw"
pygmentscodefences  = true

[permalinks]
  post = "/:year/:filename/"
  page = "/:title/"

[params]
  sitename = "Int Maker"
  disableWebFonts = false
  google_universal_analytics = "UA-10412407-14"
  google_universal_analytics_cookiedomain = "auto"
  disqus_shortname = "codejamming"
  disqus_comments = true

[[menu.main]]
    name = "Posts"
    url  = "/"
[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    url  = "/projects/"

